import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHeading,
  faBold,
  faStrikethrough,
  faUnderline,
  faItalic,
  faListOl,
  faListUl,
  faUndoAlt,
  faRedoAlt,
  faQuoteRight,
  faLink,
  faMapMarkerAlt,
  faBuilding,
  faExternalLinkSquareAlt,
  faClipboardCheck,
  faCompress,
  faExpand,
  faList,
  faMapMarkedAlt,
  faArrowRight,
  faEdit,
  faCaretUp,
  faArrowLeft,
  faHeart,
  faUser,
  faFilter,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(
  faHeading,
  faBold,
  faStrikethrough,
  faUnderline,
  faItalic,
  faListOl,
  faListUl,
  faUndoAlt,
  faRedoAlt,
  faQuoteRight,
  faLink,
  faMapMarkerAlt,
  faBuilding,
  faExternalLinkSquareAlt,
  faCompress,
  faExpand,
  faClipboardCheck,
  faList,
  faMapMarkedAlt,
  faArrowRight,
  faArrowLeft,
  faEdit,
  faCaretUp,
  faHeart,
  faUser,
  faFilter,
  faTimes
);

export default FontAwesomeIcon;
