#import "./OfficeSocialNetworkFragment.gql"

mutation createOfficeSocialNetwork($input: CreateOfficeSocialNetworkInput!) {
  createOfficeSocialNetwork(input: $input) {
    officeSocialNetwork {
      ...OfficeSocialNetworkDetail
    }
  }
}
