#import "./OfficeSocialNetworkFragment.gql"

fragment OfficeDetail on Office {
  id
  name
  website
  description
  yearFounded
  sizeNumber
  sizeId
  size {
    id
    nameShort
    nameLong
    description
  }
  officeTypologies {
    nodes {
      id
      typology {
        id
        name
        description
      }
    }
  }
  locations {
    nodes {
      id
      formattedAddress
      email
      internationalPhoneNumber
      city {
        id
        name
        countryByCountryIsocode {
          name
          iso
        }
      }
      coordinates {
        x
        y
      }
    }
  }
  officeVotes {
    totalCount
    nodes {
      id
      officeId
      userUid
    }
  }
  logoUrl
  officeSocialNetworks {
    totalCount
    nodes {
      ...OfficeSocialNetworkDetail
    }
  }
  brandfetch
}
